// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxpmvsqerrmiovbtfydi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cG12c3FlcnJtaW92YnRmeWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODM0MzcsImV4cCI6MjA2NjU1OTQzN30.PCnvpfBf8usX43UId5b_pSTWVEpF-zgT7xpHBLT_ZlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);